import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "@/components/ui/nav/nav";
import Providers from "@/hooks/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React-Next.js-shadcn/ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>made by ysmin</header>
          <Nav />
          <main className="w-[1720px] h-[1020px] flex place-content-center">
            {children}
          </main>
          <footer>
            <p>footer</p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
